### ISSUE TITLE
PumpingTargetPoint.atlas missing file

### ISSUE THREAD

**Issue by cerupcat** [nicklu717/Dribblone#40]
I'd love to try out and learn from your project, but the PumpingTargetPoint.atlas file appears to be missing. Any chance of getting that checked in? Thanks!

**Comment by nicklu717** [comment]
I've re-uploaded that file in the Resource folder.
Thanks for reminding me :)
Let me know if there's still any issue.

**Comment by Ann-726** [comment]
Hi, I am trying to learn about coreml from your project but it shows the google service-infoplist is missing. Could you please check that? Thank u very much!

**Comment by nicklu717** [comment]
Since the file contains some secret-key to access my Firebase database, it can't be uploaded in public.
https://firebase.google.com/docs/ios/setup?hl=zh-tw
This document may help you set up the project!
